export const carros = [
  { "model": "golg5", "brand": "Volkswagen", "name": "Gol G5" },
  { "model": "golquadrado", "brand": "Volkswagen", "name": "Gol Quadrado" },
  { "model": "voyageg6", "brand": "Volkswagen", "name": "Voyage G6" },
  { "model": "saveirocross", "brand": "Volkswagen", "name": "Saveiro Cross" },
  { "model": "paratisurf", "brand": "Volkswagen", "name": "Parati Surf" },
  { "model": "fusca1970", "brand": "Volkswagen", "name": "Fusca 1970" },
  { "model": "brasilia75", "brand": "Volkswagen", "name": "Brasília 1975" },
  { "model": "kombiclipper", "brand": "Volkswagen", "name": "Kombi Clipper" },
  { "model": "amarok", "brand": "Volkswagen", "name": "Amarok" },
  { "model": "santana", "brand": "Volkswagen", "name": "Santana" },

  { "model": "unomille", "brand": "Fiat", "name": "Uno Mille" },
  { "model": "palio", "brand": "Fiat", "name": "Palio" },
  { "model": "palioweekend", "brand": "Fiat", "name": "Palio Weekend" },
  { "model": "siena", "brand": "Fiat", "name": "Siena" },
  { "model": "marea", "brand": "Fiat", "name": "Marea" },
  { "model": "tempra", "brand": "Fiat", "name": "Tempra" },
  { "model": "fiat147", "brand": "Fiat", "name": "Fiat 147" },
  { "model": "toro", "brand": "Fiat", "name": "Toro" },
  { "model": "strada", "brand": "Fiat", "name": "Strada" },
  { "model": "cronos", "brand": "Fiat", "name": "Cronos" },

  { "model": "celta", "brand": "Chevrolet", "name": "Celta" },
  { "model": "corsawind", "brand": "Chevrolet", "name": "Corsa Wind" },
  { "model": "vectra", "brand": "Chevrolet", "name": "Vectra" },
  { "model": "astra", "brand": "Chevrolet", "name": "Astra" },
  { "model": "opala", "brand": "Chevrolet", "name": "Opala Diplomata" },
  { "model": "kadett", "brand": "Chevrolet", "name": "Kadett" },
  { "model": "monza", "brand": "Chevrolet", "name": "Monza" },
  { "model": "chevette", "brand": "Chevrolet", "name": "Chevette" },
  { "model": "montana", "brand": "Chevrolet", "name": "Montana" },
  { "model": "s10", "brand": "Chevrolet", "name": "S10" },

  { "model": "corolla", "brand": "Toyota", "name": "Corolla" },
  { "model": "hilux", "brand": "Toyota", "name": "Hilux" },
  { "model": "etios", "brand": "Toyota", "name": "Etios" },
  { "model": "sw4", "brand": "Toyota", "name": "SW4" },
  { "model": "yaris", "brand": "Toyota", "name": "Yaris" },

  { "model": "hb20", "brand": "Hyundai", "name": "HB20" },
  { "model": "creta", "brand": "Hyundai", "name": "Creta" },
  { "model": "ix35", "brand": "Hyundai", "name": "ix35" },

  { "model": "sandero", "brand": "Renault", "name": "Sandero" },
  { "model": "logan", "brand": "Renault", "name": "Logan" },
  { "model": "duster", "brand": "Renault", "name": "Duster" },

  { "model": "ecosport", "brand": "Ford", "name": "EcoSport" },
  { "model": "ka", "brand": "Ford", "name": "Ka" },
  { "model": "fiesta", "brand": "Ford", "name": "Fiesta" },
  { "model": "escort", "brand": "Ford", "name": "Escort" },
  { "model": "delrey", "brand": "Ford", "name": "Del Rey" },
  { "model": "corcel2", "brand": "Ford", "name": "Corcel II" }
]